version: '3'

services : 
  mongodb :
    container_name: riot_MONGO
    image : mongo:latest
    volumes:
        - ./data:/data/import
    ports :
       - "27017:27017"
  neo4j:
    container_name: riot_NEO4J
    image: neo4j:latest
    environment:
       - "NEO4J_AUTH:neo4j/esgi_password"
    cap_add:
       - SYS_RESOURCE
    ports:
       - "7474:7474"
       - "7687:7687"
  python:
    container_name: riot_PYTHON
    build: docker/python
    volumes: 
      - ./python:/home/jovyan/work/python
      - ./data:/home/jovyan/work/data
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.password='sha1:f3d8da898ad8:b0ceb6c890232f1c122f68077dec74edec277f82'"
